"""PostgreSQL persistence for the VAT pipeline."""

from __future__ import annotations

from collections.abc import Iterable

from de13_tva.importer import VatRecord
from de13_tva.settings import database_config
from de13_tva.vies import INDETERMINATE_VIES, ViesVerification

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS vat_records (
    source_id integer PRIMARY KEY,
    raison_sociale text NOT NULL,
    pays_declare_brut text NOT NULL,
    pays_declare_normalise text NOT NULL,
    numero_tva_brut text NOT NULL,
    numero_tva_nettoye text NOT NULL,
    date_saisie date,
    source_saisie text NOT NULL,
    structure_verdict text NOT NULL,
    structure_reason text NOT NULL,
    needs_human_review boolean NOT NULL DEFAULT false,
    human_review_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vat_records_numero_tva_nettoye
    ON vat_records (numero_tva_nettoye);

CREATE INDEX IF NOT EXISTS idx_vat_records_structure
    ON vat_records (structure_verdict, structure_reason);

CREATE OR REPLACE VIEW vies_candidates AS
SELECT DISTINCT ON (numero_tva_nettoye)
    numero_tva_nettoye,
    pays_declare_normalise,
    min(source_id) OVER (PARTITION BY numero_tva_nettoye) AS first_source_id,
    count(*) OVER (PARTITION BY numero_tva_nettoye) AS source_rows_count
FROM vat_records
WHERE structure_verdict = 'valid'
  AND numero_tva_nettoye <> ''
ORDER BY numero_tva_nettoye, source_id;

CREATE TABLE IF NOT EXISTS vies_verifications (
    numero_tva_nettoye text PRIMARY KEY,
    country_code text NOT NULL,
    vat_number text NOT NULL,
    vies_verdict text NOT NULL,
    checked_at timestamptz NOT NULL,
    http_status integer,
    response_time_ms integer,
    response_payload jsonb,
    error_message text,
    origin text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vies_verifications_verdict
    ON vies_verifications (vies_verdict);

CREATE INDEX IF NOT EXISTS idx_vies_verifications_checked_at
    ON vies_verifications (checked_at);

CREATE TABLE IF NOT EXISTS vies_attempts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_tva_nettoye text NOT NULL,
    country_code text NOT NULL,
    vat_number text NOT NULL,
    vies_verdict text NOT NULL,
    checked_at timestamptz NOT NULL,
    http_status integer,
    response_time_ms integer,
    response_payload jsonb,
    error_message text,
    origin text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vies_attempts_numero
    ON vies_attempts (numero_tva_nettoye);

CREATE INDEX IF NOT EXISTS idx_vies_attempts_checked_at
    ON vies_attempts (checked_at);

INSERT INTO vies_attempts (
    numero_tva_nettoye,
    country_code,
    vat_number,
    vies_verdict,
    checked_at,
    http_status,
    response_time_ms,
    response_payload,
    error_message,
    origin
)
SELECT
    vv.numero_tva_nettoye,
    vv.country_code,
    vv.vat_number,
    vv.vies_verdict,
    vv.checked_at,
    vv.http_status,
    vv.response_time_ms,
    vv.response_payload,
    vv.error_message,
    vv.origin
FROM vies_verifications vv
WHERE NOT EXISTS (
    SELECT 1
    FROM vies_attempts va
    WHERE va.numero_tva_nettoye = vv.numero_tva_nettoye
      AND va.checked_at = vv.checked_at
      AND va.origin = vv.origin
);

DELETE FROM vies_verifications
WHERE vies_verdict = 'indetermine';

CREATE TABLE IF NOT EXISTS human_review_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source text NOT NULL,
    input_raw text NOT NULL,
    numero_tva_nettoye text NOT NULL,
    review_reason text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source, input_raw, numero_tva_nettoye, review_reason)
);

CREATE INDEX IF NOT EXISTS idx_human_review_items_numero
    ON human_review_items (numero_tva_nettoye);
"""

UPSERT_SQL = """
INSERT INTO vat_records (
    source_id,
    raison_sociale,
    pays_declare_brut,
    pays_declare_normalise,
    numero_tva_brut,
    numero_tva_nettoye,
    date_saisie,
    source_saisie,
    structure_verdict,
    structure_reason,
    needs_human_review,
    human_review_reason
) VALUES (
    %(source_id)s,
    %(raison_sociale)s,
    %(pays_declare_brut)s,
    %(pays_declare_normalise)s,
    %(numero_tva_brut)s,
    %(numero_tva_nettoye)s,
    %(date_saisie)s,
    %(source_saisie)s,
    %(structure_verdict)s,
    %(structure_reason)s,
    %(needs_human_review)s,
    %(human_review_reason)s
)
ON CONFLICT (source_id) DO UPDATE SET
    raison_sociale = EXCLUDED.raison_sociale,
    pays_declare_brut = EXCLUDED.pays_declare_brut,
    pays_declare_normalise = EXCLUDED.pays_declare_normalise,
    numero_tva_brut = EXCLUDED.numero_tva_brut,
    numero_tva_nettoye = EXCLUDED.numero_tva_nettoye,
    date_saisie = EXCLUDED.date_saisie,
    source_saisie = EXCLUDED.source_saisie,
    structure_verdict = EXCLUDED.structure_verdict,
    structure_reason = EXCLUDED.structure_reason,
    needs_human_review = EXCLUDED.needs_human_review,
    human_review_reason = EXCLUDED.human_review_reason,
    updated_at = now();
"""


def connect():
    """Open a psycopg connection using project settings."""
    import psycopg

    return psycopg.connect(**database_config())


def ensure_schema(conn) -> None:
    with conn.cursor() as cursor:
        cursor.execute(SCHEMA_SQL)
    conn.commit()


def upsert_records(conn, records: Iterable[VatRecord]) -> int:
    count = 0
    with conn.cursor() as cursor:
        for record in records:
            cursor.execute(UPSERT_SQL, record.__dict__)
            count += 1
    conn.commit()
    return count


def fetch_structural_report(conn) -> dict[str, object]:
    with conn.cursor() as cursor:
        cursor.execute("SELECT count(*) FROM vat_records")
        total_rows = cursor.fetchone()[0]

        cursor.execute(
            """
            SELECT structure_reason, count(*)
            FROM vat_records
            GROUP BY structure_reason
            ORDER BY count(*) DESC, structure_reason
            """
        )
        by_reason = cursor.fetchall()

        cursor.execute(
            """
            SELECT count(DISTINCT NULLIF(numero_tva_nettoye, ''))
            FROM vat_records
            """
        )
        unique_cleaned = cursor.fetchone()[0]

        cursor.execute("SELECT count(*) FROM vies_candidates")
        candidates = cursor.fetchone()[0]

    return {
        "total_rows": total_rows,
        "by_reason": by_reason,
        "unique_cleaned": unique_cleaned,
        "vies_candidates": candidates,
        "vies_calls_avoided": total_rows - candidates,
    }


def fetch_human_review_rows(conn) -> list[dict[str, object]]:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            SELECT
                source_id,
                raison_sociale,
                pays_declare_brut,
                pays_declare_normalise,
                numero_tva_brut,
                numero_tva_nettoye,
                structure_reason,
                human_review_reason
            FROM vat_records
            WHERE needs_human_review = true
            ORDER BY source_id
            """
        )
        columns = [column.name for column in cursor.description]
        return [dict(zip(columns, row, strict=True)) for row in cursor.fetchall()]


def fetch_vies_candidates_for_verification(
    conn,
    *,
    limit: int | None,
    refresh_days: int | None,
    force_refresh: bool,
) -> list[dict[str, object]]:
    filters = []
    params: dict[str, object] = {}
    if not force_refresh:
        if refresh_days is None:
            filters.append(
                """
                vv.numero_tva_nettoye IS NULL
                AND latest_attempt.checked_at IS NULL
                """
            )
        else:
            filters.append(
                """
                (
                    coalesce(latest_attempt.checked_at, vv.checked_at) IS NULL
                    OR coalesce(latest_attempt.checked_at, vv.checked_at)
                        < now() - (%(refresh_days)s * interval '1 day')
                )
                """
            )
            params["refresh_days"] = refresh_days

    where_clause = f"WHERE {' AND '.join(filters)}" if filters else ""
    limit_clause = "LIMIT %(limit)s" if limit is not None else ""
    if limit is not None:
        params["limit"] = limit

    with conn.cursor() as cursor:
        cursor.execute(
            f"""
            SELECT
                vc.numero_tva_nettoye,
                vc.pays_declare_normalise,
                vc.first_source_id,
                vc.source_rows_count
            FROM vies_candidates vc
            LEFT JOIN vies_verifications vv
                ON vv.numero_tva_nettoye = vc.numero_tva_nettoye
            LEFT JOIN LATERAL (
                SELECT va.checked_at
                FROM vies_attempts va
                WHERE va.numero_tva_nettoye = vc.numero_tva_nettoye
                ORDER BY va.checked_at DESC, va.id DESC
                LIMIT 1
            ) latest_attempt ON true
            {where_clause}
            ORDER BY vc.first_source_id
            {limit_clause}
            """,
            params,
        )
        columns = [column.name for column in cursor.description]
        return [dict(zip(columns, row, strict=True)) for row in cursor.fetchall()]


def upsert_vies_verification(
    conn,
    verification: ViesVerification,
    *,
    origin: str,
) -> None:
    from psycopg.types.json import Jsonb

    params = _vies_params(verification, origin, Jsonb)
    with conn.cursor() as cursor:
        cursor.execute(
            """
            INSERT INTO vies_attempts (
                numero_tva_nettoye,
                country_code,
                vat_number,
                vies_verdict,
                checked_at,
                http_status,
                response_time_ms,
                response_payload,
                error_message,
                origin
            ) VALUES (
                %(numero_tva_nettoye)s,
                %(country_code)s,
                %(vat_number)s,
                %(vies_verdict)s,
                %(checked_at)s,
                %(http_status)s,
                %(response_time_ms)s,
                %(response_payload)s,
                %(error_message)s,
                %(origin)s
            )
            """,
            params,
        )
        if verification.vies_verdict == INDETERMINATE_VIES:
            conn.commit()
            return
        cursor.execute(
            """
            INSERT INTO vies_verifications (
                numero_tva_nettoye,
                country_code,
                vat_number,
                vies_verdict,
                checked_at,
                http_status,
                response_time_ms,
                response_payload,
                error_message,
                origin
            ) VALUES (
                %(numero_tva_nettoye)s,
                %(country_code)s,
                %(vat_number)s,
                %(vies_verdict)s,
                %(checked_at)s,
                %(http_status)s,
                %(response_time_ms)s,
                %(response_payload)s,
                %(error_message)s,
                %(origin)s
            )
            ON CONFLICT (numero_tva_nettoye) DO UPDATE SET
                country_code = EXCLUDED.country_code,
                vat_number = EXCLUDED.vat_number,
                vies_verdict = EXCLUDED.vies_verdict,
                checked_at = EXCLUDED.checked_at,
                http_status = EXCLUDED.http_status,
                response_time_ms = EXCLUDED.response_time_ms,
                response_payload = EXCLUDED.response_payload,
                error_message = EXCLUDED.error_message,
                origin = EXCLUDED.origin,
                updated_at = now()
            """,
            params,
        )
    conn.commit()


def insert_vies_attempt(
    conn,
    verification: ViesVerification,
    *,
    origin: str,
) -> None:
    from psycopg.types.json import Jsonb

    with conn.cursor() as cursor:
        cursor.execute(
            """
            INSERT INTO vies_attempts (
                numero_tva_nettoye,
                country_code,
                vat_number,
                vies_verdict,
                checked_at,
                http_status,
                response_time_ms,
                response_payload,
                error_message,
                origin
            ) VALUES (
                %(numero_tva_nettoye)s,
                %(country_code)s,
                %(vat_number)s,
                %(vies_verdict)s,
                %(checked_at)s,
                %(http_status)s,
                %(response_time_ms)s,
                %(response_payload)s,
                %(error_message)s,
                %(origin)s
            )
            """,
            _vies_params(verification, origin, Jsonb),
        )
    conn.commit()


def _vies_params(verification: ViesVerification, origin: str, jsonb_type) -> dict:
    return {
        **verification.__dict__,
        "response_payload": (
            jsonb_type(verification.response_payload)
            if verification.response_payload is not None
            else None
        ),
        "origin": origin,
    }


def fetch_stored_vies_verification(
    conn,
    numero_tva_nettoye: str,
) -> dict[str, object] | None:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            SELECT
                numero_tva_nettoye,
                country_code,
                vat_number,
                vies_verdict,
                checked_at,
                http_status,
                response_time_ms,
                response_payload,
                error_message,
                origin
            FROM vies_verifications
            WHERE numero_tva_nettoye = %(numero_tva_nettoye)s
            """,
            {"numero_tva_nettoye": numero_tva_nettoye},
        )
        row = cursor.fetchone()
        if row is None:
            return None
        columns = [column.name for column in cursor.description]
        return dict(zip(columns, row, strict=True))


def record_human_review_item(
    conn,
    *,
    source: str,
    input_raw: str,
    numero_tva_nettoye: str,
    review_reason: str,
) -> None:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            INSERT INTO human_review_items (
                source,
                input_raw,
                numero_tva_nettoye,
                review_reason
            ) VALUES (
                %(source)s,
                %(input_raw)s,
                %(numero_tva_nettoye)s,
                %(review_reason)s
            )
            ON CONFLICT (source, input_raw, numero_tva_nettoye, review_reason)
            DO NOTHING
            """,
            {
                "source": source,
                "input_raw": input_raw,
                "numero_tva_nettoye": numero_tva_nettoye,
                "review_reason": review_reason,
            },
        )
    conn.commit()


def fetch_phase2_human_review_rows(conn) -> list[dict[str, object]]:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            SELECT source, input_raw, numero_tva_nettoye, review_reason, created_at
            FROM human_review_items
            ORDER BY created_at, id
            """
        )
        columns = [column.name for column in cursor.description]
        return [dict(zip(columns, row, strict=True)) for row in cursor.fetchall()]


def fetch_reconciliation_details(conn) -> list[dict[str, object]]:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            SELECT
                vr.source_id,
                vr.raison_sociale,
                vr.pays_declare_brut,
                vr.pays_declare_normalise,
                vr.numero_tva_brut,
                vr.numero_tva_nettoye,
                vr.structure_verdict,
                vr.structure_reason,
                CASE
                    WHEN vr.structure_verdict = 'valid'
                         AND vv.vies_verdict IN ('valide', 'invalide')
                        THEN vv.vies_verdict
                    ELSE 'indetermine'
                END AS final_verdict,
                CASE
                    WHEN vr.structure_verdict <> 'valid' THEN 'structural_reject'
                    WHEN vv.numero_tva_nettoye IS NULL THEN 'pending_vies'
                    ELSE vv.origin
                END AS final_origin,
                vv.checked_at,
                CASE
                    WHEN vv.checked_at IS NULL THEN NULL
                    ELSE floor(extract(epoch FROM (now() - vv.checked_at)) / 86400)::int
                END AS freshness_days,
                (
                    vr.needs_human_review
                    OR vv.vies_verdict = 'indetermine'
                ) AS needs_human_review,
                (
                    vr.structure_verdict = 'valid'
                    AND vv.numero_tva_nettoye IS NULL
                ) AS needs_vies_verification,
                CASE
                    WHEN vr.human_review_reason IS NOT NULL
                        THEN vr.human_review_reason
                    WHEN vv.vies_verdict = 'indetermine'
                        THEN coalesce(vv.error_message, 'VIES indetermine')
                    ELSE NULL
                END AS review_reason
            FROM vat_records vr
            LEFT JOIN vies_verifications vv
                ON vv.numero_tva_nettoye = vr.numero_tva_nettoye
            ORDER BY vr.source_id
            """
        )
        columns = [column.name for column in cursor.description]
        return [dict(zip(columns, row, strict=True)) for row in cursor.fetchall()]


def fetch_reconciliation_report(conn) -> dict[str, object]:
    structural = fetch_structural_report(conn)
    with conn.cursor() as cursor:
        cursor.execute("SELECT count(*) FROM vies_verifications")
        verifications_total = cursor.fetchone()[0]

        cursor.execute("SELECT count(*) FROM vies_attempts")
        attempts_total = cursor.fetchone()[0]

        cursor.execute(
            """
            SELECT vies_verdict, count(*)
            FROM vies_verifications
            GROUP BY vies_verdict
            ORDER BY vies_verdict
            """
        )
        by_vies_verdict = cursor.fetchall()

        cursor.execute(
            """
            SELECT vies_verdict, count(*)
            FROM vies_attempts
            GROUP BY vies_verdict
            ORDER BY vies_verdict
            """
        )
        by_attempt_verdict = cursor.fetchall()

        cursor.execute(
            """
            SELECT count(*)
            FROM (
                SELECT numero_tva_nettoye
                FROM vat_records
                WHERE numero_tva_nettoye <> ''
                GROUP BY numero_tva_nettoye
                HAVING count(*) > 1
            ) duplicates
            """
        )
        duplicate_numbers = cursor.fetchone()[0]

        cursor.execute("SELECT count(*) FROM vat_records WHERE needs_human_review")
        phase1_review = cursor.fetchone()[0]

        cursor.execute("SELECT count(*) FROM human_review_items")
        phase2_review = cursor.fetchone()[0]

        cursor.execute(
            """
            SELECT count(*)
            FROM vat_records vr
            LEFT JOIN vies_verifications vv
                ON vv.numero_tva_nettoye = vr.numero_tva_nettoye
            WHERE vr.structure_verdict = 'valid'
              AND vv.numero_tva_nettoye IS NULL
            """
        )
        pending_vies = cursor.fetchone()[0]

        cursor.execute(
            """
            SELECT count(*)
            FROM vies_candidates vc
            LEFT JOIN vies_verifications vv
                ON vv.numero_tva_nettoye = vc.numero_tva_nettoye
            WHERE vv.numero_tva_nettoye IS NULL
            """
        )
        pending_vies_unique = cursor.fetchone()[0]

        cursor.execute(
            """
            SELECT final_verdict, count(*)
            FROM (
                SELECT
                    CASE
                        WHEN vr.structure_verdict = 'valid'
                             AND vv.vies_verdict IN ('valide', 'invalide')
                            THEN vv.vies_verdict
                        ELSE 'indetermine'
                    END AS final_verdict
                FROM vat_records vr
                LEFT JOIN vies_verifications vv
                    ON vv.numero_tva_nettoye = vr.numero_tva_nettoye
            ) reconciled
            GROUP BY final_verdict
            ORDER BY final_verdict
            """
        )
        by_final_verdict = cursor.fetchall()

    return {
        **structural,
        "vies_verifications_total": verifications_total,
        "vies_attempts_total": attempts_total,
        "by_vies_verdict": by_vies_verdict,
        "by_attempt_verdict": by_attempt_verdict,
        "by_final_verdict": by_final_verdict,
        "duplicate_numbers": duplicate_numbers,
        "phase1_human_review": phase1_review,
        "phase2_human_review": phase2_review,
        "pending_vies": pending_vies,
        "pending_vies_unique": pending_vies_unique,
    }
